
services:
  db:
    image: postgres:14
    environment:
      POSTGRES_DB: fishingdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  web:
    build: ./backend
    command: gunicorn fishingapp.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./backend:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis

  celery:
    build: ./backend
    command: celery -A fishingapp worker --loglevel=info
    volumes:
      - ./backend:/code
    depends_on:
      - db
      - redis

volumes:
  postgres_data:
