# Generated by Django 5.1.7 on 2025-03-22 15:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catches', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='catchentry',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='catches/'),
            preserve_default=False,
        ),
    ]
