# Generated by Django 5.1.7 on 2025-03-28 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catches', '0002_catchentry_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catchentry',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='catches/MEDIA'),
        ),
    ]
