# Generated by Django 5.1.7 on 2025-03-31 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catches', '0003_alter_catchentry_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='catchentry',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='catchentry',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
