# Generated by Django 5.1.7 on 2025-04-01 09:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catches', '0004_catchentry_latitude_catchentry_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='catchentry',
            name='time_caught',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
