# Generated by Django 5.1.7 on 2025-04-01 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catches', '0005_catchentry_time_caught'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catchentry',
            name='time_caught',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
