# Generated by Django 5.1.7 on 2025-04-01 09:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catches', '0006_alter_catchentry_time_caught'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catchentry',
            name='time_caught',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
