# Generated by Django 5.1.7 on 2025-04-01 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catches', '0007_alter_catchentry_time_caught'),
    ]

    operations = [
        migrations.AddField(
            model_name='catchentry',
            name='precipitation',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='catchentry',
            name='temperature',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='catchentry',
            name='weather_code',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='catchentry',
            name='windspeed',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
